name: flutter_dignal_2025
description: Flutter app for iot course of dignal.

publish_to: 'none'

version: 2.1.0

environment:
  sdk: 3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
  